function G = G_func(in1,in2)
%G_FUNC
%    G = G_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:06

%
Mh = in2(:,3);
Ms = in2(:,4);
Mt = in2(:,5);
g = in2(:,6);
ls = in2(:,7);
lt = in2(:,8);
rs = in2(:,9);
rt = in2(:,10);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = cos(x3);
t3 = cos(x4);
t4 = cos(x5);
t5 = cos(x6);
t6 = sin(x3);
t7 = sin(x4);
t8 = sin(x5);
t9 = sin(x6);
t10 = ls+lt;
t11 = ls+rt;
t12 = t2.*t3;
t13 = t2.*t7;
t14 = t3.*t6;
t15 = t6.*t7;
t16 = t3-1.0;
t17 = t4-1.0;
t18 = t5-1.0;
t19 = ls.*t13;
t20 = ls.*t14;
t21 = -t15;
t22 = ls.*t6.*t16;
t23 = t13+t14;
t24 = t12+t21;
t25 = t4.*t23;
t26 = t8.*t23;
t27 = t10.*t23;
t28 = t11.*t23;
t29 = t4.*t24;
t30 = t8.*t24;
t31 = -t26;
t32 = t10.*t25;
t33 = -t27;
t34 = -t28;
t36 = t17.*t27;
t35 = t10.*t30;
t37 = t25+t30;
t38 = t29+t31;
t41 = -t9.*(t26-t29);
t39 = t5.*t37;
t40 = t11.*t37;
t43 = ls.*t41;
t44 = ls.*t18.*t37;
t42 = -t40;
t45 = t39+t41;
t46 = rs.*t45;
t47 = -t46;
G = [0.0;Mh.*g+Ms.*g.*2.0+Mt.*g.*2.0;Ms.*g.*(t19+t22+t35+t36+t43+t44+t47)+Mt.*g.*(t19+t22+t35+t36+t42)+Mh.*g.*(t19+t22+t33)+Mt.*g.*(t19+t22+t34)-Ms.*g.*rs.*t6;Ms.*g.*(t19+t20+t35+t36+t43+t44+t47)+Mt.*g.*(t19+t20+t35+t36+t42)+Mh.*g.*(t19+t20+t33)+Mt.*g.*(t19+t20+t34);Ms.*g.*(t32+t35+t43+t44+t47)+Mt.*g.*(t32+t35+t42);-Ms.*g.*(t46-ls.*t39+ls.*t9.*(t26-t29))];
