function Aswap = A_Swap_func(in1,in2)
%A_SWAP_FUNC
%    ASWAP = A_SWAP_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-May-2020 10:16:53

a = in2(:,4);
b = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = a+b;
t3 = x3+x4;
t4 = cos(t3);
t5 = sin(t3);
Aswap = reshape([1.0,0.0,0.0,1.0,t2.*(t4-cos(x3)),t2.*(t5-sin(x3)),t2.*t4,t2.*t5],[2,4]);
