function out1 = Adot_SSupp_func(in1,in2)
%ADOT_SSUPP_FUNC
%    OUT1 = ADOT_SSUPP_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-May-2020 10:16:53

out1 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,4]);
