function velAst = Ankle_St_vel_func(in1)
%ANKLE_ST_VEL_FUNC
%    VELAST = ANKLE_ST_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Oct-2019 12:19:56

%Prosthesis file. Needs state and parameters as inputs
global flowdata
in2 =  flowdata.Parameters.Biped.asvector;
la = in2(:,10);
x3 = in1(3,:);
x4 = in1(4,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
t2 = x3+x4;
t3 = x8+x9;
t4 = cos(t2);
t5 = sin(t2);
t6 = t3.*t4;
t7 = t3.*t5;
t8 = -t7;
velAst = reshape([t8,t6,0.0,0.0,-t6,t8,0.0,0.0,0.0,0.0,0.0,0.0,x6-la.*x8.*cos(x3),x7-la.*x8.*sin(x3),0.0,0.0],[4,4]);
