function velAnkle = Ankle_vel_func(in1,in2)
%ANKLE_VEL_FUNC
%    VELANKLE = ANKLE_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 10:54:29

%Prosthesis file. Needs state and parameters as inputs
ls = in2(:,4);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
velAnkle = [x5-ls.*x7.*cos(x3);x6-ls.*x7.*sin(x3);0.0;0.0;0.0;cos(x3+x4).*(x7+x8)];
