function js1 = Ankle_St_Jacobian_func(in1)
%ANKLE_ST_JACOBIAN_FUNC
%    JS1 = ANKLE_ST_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Oct-2019 12:19:57

%Prosthesis file. Needs state and parameters as inputs
global flowdata
in2 =  flowdata.Parameters.Biped.asvector;
la = in2(:,10);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x3+x4;
t3 = cos(t2);
js1 = reshape([1.0,1.0,0.0,0.0,0.0,0.0,0.0,-la.*sin(x3),0.0,0.0,0.0,0.0,-la.*cos(x3),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t3,0.0,0.0,0.0,0.0,0.0,t3,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
