function posCoM = COM_pos_func(in1,in2)
%COM_POS_FUNC
%    POSCOM = COM_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 10:54:28

%Prosthesis file. Needs state and parameters as inputs
Mf = in2(:,2);
Ms = in2(:,1);
la = in2(:,5);
lf = in2(:,6);
ls = in2(:,4);
lt = in2(:,3);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x3);
t3 = x3+x4;
t4 = Mf+Ms;
t7 = -lt;
t5 = cos(t3);
t6 = sin(t3);
t8 = 1.0./t4;
posCoM = [(t8.*(t4.*x1.*4.0-sin(x3).*(Ms.*(la.*2.0+ls-lt.*2.0).*2.0+Mf.*ls.*4.0)-Mf.*t6.*(la.*6.0-lt.*4.0)+Mf.*lf.*t5))./4.0,t8.*(Ms.*(lt+x2+t2.*(la+ls./2.0+t7))+Mf.*(lt+x2+(lf.*t6)./4.0+ls.*t2+t5.*(la.*(3.0./2.0)+t7))),0.0];
