function posKnee = Knee_pos_func(in1,in2)
%KNEE_POS_FUNC
%    POSKNEE = KNEE_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 10:54:28

%Prosthesis file. Needs state and parameters as inputs
lt = in2(:,3);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
posKnee = [x1;lt+x2;0.0;0.0;0.0;sin(x3)];
