function velKst = Knee_St_vel_func(in1)
%KNEE_ST_VEL_FUNC
%    VELKST = KNEE_ST_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Oct-2019 12:19:56

%Prosthesis file. Needs state and parameters as inputs
global flowdata
in2 =  flowdata.Parameters.Biped.asvector;
la = in2(:,10);
ls = in2(:,9);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
t2 = x3+x4;
t3 = x8+x9;
t4 = t2+x5;
t5 = t3+x10;
t6 = cos(t4);
t7 = sin(t4);
t8 = t5.*t6;
t9 = t5.*t7;
t10 = -t9;
velKst = reshape([t10,t8,0.0,0.0,-t8,t10,0.0,0.0,0.0,0.0,0.0,0.0,x6-ls.*t3.*cos(t2)-la.*x8.*cos(x3),x7-ls.*t3.*sin(t2)-la.*x8.*sin(x3),0.0,0.0],[4,4]);
