function js2 = Knee_St_Jacobian_func(in1)
%KNEE_ST_JACOBIAN_FUNC
%    JS2 = KNEE_ST_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Oct-2019 12:19:57

%Prosthesis file. Needs state and parameters as inputs
global flowdata
in2 =  flowdata.Parameters.Biped.asvector;
la = in2(:,10);
ls = in2(:,9);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+x5;
t6 = cos(t5);
t7 = ls.*t3;
t8 = ls.*t4;
t9 = -t7;
t10 = -t8;
js2 = reshape([1.0,1.0,0.0,0.0,0.0,0.0,0.0,t10-la.*sin(x3),0.0,0.0,0.0,0.0,t9-la.*cos(x3),t10,0.0,0.0,0.0,0.0,t9,0.0,0.0,0.0,t6,0.0,0.0,0.0,0.0,0.0,t6,0.0,0.0,0.0,0.0,0.0,t6,0.0],[6,6]);
