function velKnee = Knee_vel_func(in1,in2)
%KNEE_VEL_FUNC
%    VELKNEE = KNEE_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 10:54:29

%Prosthesis file. Needs state and parameters as inputs
x3 = in1(3,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
velKnee = [x5;x6;0.0;0.0;0.0;x7.*cos(x3)];
