function LJacobCurved = Spring_Jacobian_Curved_func(in1)
%SPRING_JACOBIAN_CURVED_FUNC
%    LJACOBCURVED = SPRING_JACOBIAN_CURVED_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    17-Oct-2019 12:02:06
global flowdata
in2 =  flowdata.Parameters.Biped.asvector;
R = in2(:,12);
phi = in2(:,13);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = cos(x4);
t3 = cos(x5);
t4 = sin(phi);
t5 = x4+x5;
t6 = R.^2;
t9 = -phi;
t10 = -x4;
t7 = cos(t5);
t8 = sin(t5);
t11 = phi+t10;
t13 = t5+t9;
t17 = t3.*3.2499560856e-1;
t18 = t2.*5.1733994832e-2;
t20 = R.*t4.*1.28076e-1;
t12 = sin(t11);
t14 = cos(t13);
t15 = sin(t13);
t19 = t7.*5.152369404000001e-2;
t21 = -t20;
t16 = R.*t15.*8.0458e-1;
t22 = R.*t12.*8.078639999999999e-1;
t23 = -t22;
t24 = t6+t16+t17+t18+t19+t21+t23+3.290991701680001e-1;
t25 = 1.0./sqrt(t24);
LJacobCurved = [0.0;0.0;0.0;-t25.*(t8.*2.576184702e-2+sin(x4).*2.5866997416e-2-R.*t14.*4.0229e-1-R.*cos(t11).*4.03932e-1);t25.*(t8.*6.4038e-2+sin(x5).*4.03932e-1-R.*t14).*(-4.0229e-1);0.0;0.0;0.0];
