function LdotFlatHeel = Spring_vel_Heel_func(in1)
%SPRING_VEL_FUNC
%    LDOTFLATHEEL = SPRING_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Oct-2019 16:11:33
global flowdata
in2 =  flowdata.Parameters.Biped.asvector;
la = in2(:,10);
lf = in2(:,11);
ls = in2(:,9);
lt = in2(:,8);
x4 = in1(4,:);
x5 = in1(5,:);
x9 = in1(9,:);
x10 = in1(10,:);
t2 = cos(x4);
t3 = sin(x4);
t4 = x4+x5;
t5 = cos(t4);
t6 = sin(t4);
LdotFlatHeel = (x9.*(-la.*(ls.*t3+lt.*t6)+lf.*ls.*t2+lf.*lt.*t5)-lt.*x10.*(la.*t6-lf.*t5+ls.*sin(x5))).*1.0./sqrt(la.^2+lf.^2+ls.^2+lt.^2+ls.*lt.*cos(x5).*2.0+la.*ls.*t2.*2.0+la.*lt.*t5.*2.0+lf.*ls.*t3.*2.0+lf.*lt.*t6.*2.0);
