function LdotCurved = Spring_vel_Curved_func(in1)
%SPRING_VEL_CURVED_FUNC
%    LDOTCURVED = SPRING_VEL_CURVED_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    17-Oct-2019 12:02:01
global flowdata
in2 =  flowdata.Parameters.Biped.asvector;
R = in2(:,12);
phi = in2(:,13);
x4 = in1(4,:);
x5 = in1(5,:);
x9 = in1(9,:);
x10 = in1(10,:);
t2 = x4+x5;
t4 = -phi;
t5 = -x4;
t3 = sin(t2);
t6 = phi+t5;
t7 = t2+t4;
t8 = cos(t7);
t11 = t3.*2.576184702e-2;
t9 = R.*t8.*4.0229e-1;
t10 = -t9;
LdotCurved = -(x9.*(t10+t11+sin(x4).*2.5866997416e-2-R.*cos(t6).*4.03932e-1)+x10.*(t10+t11+sin(x5).*1.6249780428e-1)).*1.0./sqrt(cos(t2).*5.152369404000001e-2+cos(x4).*5.1733994832e-2+cos(x5).*3.2499560856e-1-R.*sin(phi).*1.28076e-1-R.*sin(t6).*8.078639999999999e-1+R.*sin(t7).*8.0458e-1+R.^2+3.290991701680001e-1);
