function LCurved = Spring_Length_Curved_func(in1)
%SPRING_LENGTH_CURVED_FUNC
%    LCURVED = SPRING_LENGTH_CURVED_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    17-Oct-2019 12:02:07
global flowdata
in2 =  flowdata.Parameters.Biped.asvector;
R = in2(:,12);
phi = in2(:,13);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = x4+x5;
t3 = phi-x4;
LCurved = sqrt(cos(t2).*5.152369404000001e-2+cos(x4).*5.1733994832e-2+cos(x5).*3.2499560856e-1-R.*sin(phi).*1.28076e-1-R.*sin(t3).*8.078639999999999e-1+R.^2+R.*sin(-phi+t2).*8.0458e-1+3.290991701680001e-1);
