function velToest = Toe_St_vel_func(in1)
%TOE_ST_VEL_FUNC
%    VELTOEST = TOE_ST_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Oct-2019 12:19:56

%Prosthesis file. Needs state and parameters as inputs
global flowdata
in2 =  flowdata.Parameters.Biped.asvector;
lf = in2(:,11);
x3 = in1(3,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = cos(x3);
t3 = sin(x3);
t4 = t2.*x8;
t5 = t3.*x8;
t6 = -t5;
velToest = reshape([t6,t4,0.0,0.0,-t4,t6,0.0,0.0,0.0,0.0,0.0,0.0,x6+lf.*t6,x7+lf.*t4,0.0,0.0],[4,4]);
