function js0 = Toe_St_Jacobian_func(in1)
%TOE_ST_JACOBIAN_FUNC
%    JS0 = TOE_ST_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    14-Oct-2019 12:19:57

%Prosthesis file. Needs state and parameters as inputs
global flowdata
in2 =  flowdata.Parameters.Biped.asvector;
lf = in2(:,11);
x3 = in1(3,:);
t2 = cos(x3);
js0 = reshape([1.0,1.0,0.0,0.0,0.0,0.0,0.0,lf.*t2,0.0,0.0,0.0,0.0,-lf.*sin(x3),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
