function js1 = Ankle_St_Jacobian_func(in1,in2)
%ANKLE_ST_JACOBIAN_FUNC
%    JS1 = ANKLE_ST_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Sep-2020 09:35:38

la = in2(:,8);
x3 = in1(3,:);
js1 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-la.*cos(x3),0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-la.*sin(x3),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
