function posAst = Ankle_St_pos_func(in1,in2)
%ANKLE_ST_POS_FUNC
%    POSAST = ANKLE_ST_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Sep-2020 21:44:00

la = in2(:,8);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
posAst = reshape([t3,t4,0.0,0.0,-t4,t3,0.0,0.0,0.0,0.0,1.0,0.0,x1-la.*sin(x3),x2+la.*cos(x3),0.0,1.0],[4,4]);
