function velAst = Ankle_St_vel_func(in1,in2)
%ANKLE_ST_VEL_FUNC
%    VELAST = ANKLE_ST_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Sep-2020 21:44:03

la = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = x3+x4;
t3 = x11+x12;
t4 = cos(t2);
t5 = sin(t2);
t6 = t3.*t4;
t7 = t3.*t5;
t8 = -t7;
velAst = reshape([t8,t6,0.0,0.0,-t6,t8,0.0,0.0,0.0,0.0,0.0,0.0,x9-la.*x11.*cos(x3),x10-la.*x11.*sin(x3),0.0,0.0],[4,4]);
