function posAsw = Ankle_Sw_pos_func(in1,in2)
%ANKLE_SW_POS_FUNC
%    POSASW = ANKLE_SW_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Sep-2020 21:44:01

la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
t2 = x3+x4;
t3 = t2+x5;
t4 = t3+x6;
t5 = t4+x7;
t6 = cos(t5);
t7 = sin(t5);
posAsw = reshape([t6,t7,0.0,0.0,-t7,t6,0.0,0.0,0.0,0.0,1.0,0.0,x1+ls.*t7-ls.*sin(t2)-lt.*sin(t3)+lt.*sin(t4)-la.*sin(x3),x2-ls.*t6+ls.*cos(t2)+lt.*cos(t3)-lt.*cos(t4)+la.*cos(x3),0.0,1.0],[4,4]);
