function js6 = Ankle_Sw_Jacobian_func(in1)
%ANKLE_SW_JACOBIAN_FUNC
%    JS6 = ANKLE_SW_JACOBIAN_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Sep-2019 18:19:32

%7 Link Flat Foot with Double Support file. Only needs state as inputs, parameters are already substituted in
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+x5;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+x6;
t18 = t3.*(1.07e+2./2.5e+2);
t19 = t4.*(1.07e+2./2.5e+2);
t9 = cos(t8);
t10 = sin(t8);
t11 = t8+x7;
t21 = -t18;
t22 = -t19;
t23 = t6.*(1.07e+2./2.5e+2);
t24 = t7.*(1.07e+2./2.5e+2);
t12 = cos(t11);
t13 = sin(t11);
t14 = t11+x8;
t27 = t9.*(1.07e+2./2.5e+2);
t28 = t10.*(1.07e+2./2.5e+2);
t29 = -t23;
t30 = -t24;
t15 = cos(t14);
t16 = sin(t14);
t32 = t12.*(1.07e+2./2.5e+2);
t33 = t13.*(1.07e+2./2.5e+2);
t17 = t16./5.0;
t20 = t15./5.0;
t26 = t16.*(7.0./1.0e+2);
t31 = t15.*(7.0./1.0e+2);
t25 = -t20;
js6 = reshape([1.0,t17+t31+t32,t25+t26+t28+t30+t33,0.0,0.0,0.0,0.0,t17+t31,t25+t26+t28+t33,0.0,0.0,0.0,t17+t21+t27+t29+t31+t32-cos(x3).*(7.0./1.0e+2),0.0,t25+t26+t33,0.0,0.0,0.0,t17+t21+t27+t29+t31+t32,1.0,t25+t26,0.0,0.0,0.0,t17+t27+t29+t31+t32,t22+t25+t26+t28+t30+t33-sin(x3).*(7.0./1.0e+2),0.0,0.0,0.0,0.0,t17+t27+t31+t32,t22+t25+t26+t28+t30+t33,0.0,0.0,0.0,0.0],[6,6]);
