function js6 = Ankle_Sw_Jacobian_func(in1,in2)
%ANKLE_SW_JACOBIAN_FUNC
%    JS6 = ANKLE_SW_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Sep-2020 09:35:39

la = in2(:,8);
lf = in2(:,7);
ls = in2(:,6);
lt = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+x5;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+x6;
t9 = ls.*t3;
t10 = ls.*t4;
t11 = cos(t8);
t12 = sin(t8);
t13 = t8+x7;
t14 = lt.*t7;
t18 = lt.*t6;
t21 = -t9;
t22 = -t10;
t15 = cos(t13);
t16 = sin(t13);
t17 = t13+x8;
t19 = lt.*t11;
t20 = lt.*t12;
t25 = -t14;
t28 = -t18;
t23 = cos(t17);
t24 = sin(t17);
t26 = ls.*t15;
t27 = ls.*t16;
t29 = la.*t23;
t30 = lf.*t23;
t31 = la.*t24;
t32 = lf.*t24;
t33 = -t32;
js6 = reshape([1.0,t26+t29+t33,t20+t25+t27+t30+t31,0.0,0.0,0.0,0.0,t29+t33,t20+t27+t30+t31,0.0,0.0,0.0,t19+t21+t26+t28+t29+t33-la.*cos(x3),0.0,t27+t30+t31,0.0,0.0,0.0,t19+t21+t26+t28+t29+t33,1.0,t30+t31,0.0,0.0,0.0,t19+t26+t28+t29+t33,t20+t22+t25+t27+t30+t31-la.*sin(x3),0.0,0.0,0.0,0.0,t19+t26+t29+t33,t20+t22+t25+t27+t30+t31,0.0,0.0,0.0,0.0],[6,6]);
