function velCoM = COM_vel_func(in1)
%COM_VEL_FUNC
%    VELCOM = COM_VEL_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Sep-2020 10:10:52

x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
x13 = in1(13,:);
x14 = in1(14,:);
x15 = in1(15,:);
x16 = in1(16,:);
t2 = x3+x4;
t3 = x11+x12;
t4 = t2+x5;
t5 = t3+x13;
t6 = t4+x6;
t7 = t5+x14;
t8 = t6+x7;
t9 = t7+x15;
t10 = t8+x8;
t11 = t9+x16;
velCoM = [x9-t3.*cos(t2).*4.066774979423868e-1-t5.*cos(t4).*3.590867160493827e-1+t7.*cos(t6).*6.891328395061729e-2+t9.*cos(t8).*2.132250205761317e-2+t11.*cos(t10).*5.761316872427984e-4-x11.*cos(x3).*6.94238683127572e-2,x10-t3.*sin(t2).*4.066774979423868e-1-t5.*sin(t4).*3.590867160493827e-1+t7.*sin(t6).*6.891328395061729e-2+t9.*sin(t8).*2.132250205761317e-2+t11.*sin(t10).*5.761316872427984e-4-x11.*sin(x3).*6.94238683127572e-2,0.0];
