function posCoM = COM_pos_func(in1,in2)
%COM_POS_FUNC
%    POSCOM = COM_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Sep-2020 21:44:02

Mf = in2(:,4);
Mh = in2(:,3);
Ms = in2(:,2);
Mt = in2(:,1);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = x3+x4;
t3 = Mf.*2.0;
t4 = Mf.*3.0;
t5 = Mf.*4.0;
t6 = Mh.*2.0;
t7 = Ms.*2.0;
t8 = Ms.*3.0;
t9 = Ms.*4.0;
t10 = Mt.*2.0;
t11 = Mt.*4.0;
t12 = t2+x5;
t22 = Mh+t3+t7+t10;
t23 = t3+t6+t8+t11;
t24 = t4+t6+t9+t11;
t25 = t5+t6+t9+t11;
t13 = cos(t12);
t14 = sin(t12);
t15 = t12+x6;
t26 = 1.0./t22;
t16 = cos(t15);
t17 = sin(t15);
t18 = t15+x7;
t19 = cos(t18);
t20 = sin(t18);
t21 = t18+x8;
posCoM = [(t26.*(t25.*x1+Mf.*la.*sin(t21)-ls.*t23.*sin(t2)-la.*t24.*sin(x3)-Mf.*lt.*t14.*2.0-Mh.*lt.*t14.*2.0+Ms.*ls.*t20-Ms.*lt.*t14.*2.0-Mt.*lt.*t14.*3.0+Mt.*lt.*t17+ls.*t3.*t20+lt.*t3.*t17+lt.*t7.*t17))./2.0,(t26.*(t25.*x2+ls.*t23.*cos(t2)+la.*t24.*cos(x3)-Mf.*ls.*t19.*2.0-Mf.*lt.*t16.*2.0-Ms.*ls.*t19-Ms.*lt.*t16.*2.0+Mt.*lt.*t13.*3.0-Mt.*lt.*t16+lt.*t3.*t13+lt.*t6.*t13+lt.*t7.*t13-Mf.*la.*cos(t21)))./2.0,0.0];
