function js3 = Hip_Jacobian_func(in1,in2)
%HIP_JACOBIAN_FUNC
%    JS3 = HIP_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Sep-2020 21:44:06

la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+x5;
t6 = cos(t5);
t7 = sin(t5);
t8 = ls.*t3;
t9 = ls.*t4;
t10 = lt.*t7;
t11 = lt.*t6;
t12 = -t8;
t13 = -t9;
t14 = -t10;
t15 = -t11;
js3 = reshape([1.0,0.0,t14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t12+t15-la.*cos(x3),0.0,0.0,0.0,0.0,0.0,t12+t15,1.0,0.0,0.0,0.0,0.0,t15,t13+t14-la.*sin(x3),0.0,0.0,0.0,0.0,0.0,t13+t14,0.0,0.0,0.0,0.0],[6,6]);
