function js3dot = Hip_Jacobian_Dot_func(in1,in2)
%HIP_JACOBIAN_DOT_FUNC
%    JS3DOT = HIP_JACOBIAN_DOT_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    26-Sep-2020 11:04:23

la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x11 = in1(11,:);
x12 = in1(12,:);
x13 = in1(13,:);
t2 = x3+x4;
t3 = x11+x12;
t4 = cos(t2);
t5 = sin(t2);
t6 = t2+x5;
t7 = t3+x13;
t8 = cos(t6);
t9 = sin(t6);
t10 = ls.*t3.*t4;
t11 = ls.*t3.*t5;
t12 = lt.*t7.*t8;
t13 = lt.*t7.*t9;
t14 = -t10;
t15 = -t12;
js3dot = reshape([0.0,0.0,0.0,0.0,t11+t13+la.*x11.*sin(x3),t14+t15-la.*x11.*cos(x3),t11+t13,t14+t15,t13,t15,0.0,0.0,0.0,0.0,0.0,0.0],[2,8]);
