function js2 = Knee_St_Jacobian_func(in1,in2)
%KNEE_ST_JACOBIAN_FUNC
%    JS2 = KNEE_ST_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Sep-2020 21:44:06

la = in2(:,8);
ls = in2(:,6);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
t5 = ls.*t3;
t6 = ls.*t4;
t7 = -t5;
t8 = -t6;
js2 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t7-la.*cos(x3),0.0,0.0,0.0,0.0,0.0,t7,1.0,0.0,0.0,0.0,0.0,0.0,t8-la.*sin(x3),0.0,0.0,0.0,0.0,0.0,t8,0.0,0.0,0.0,0.0],[6,6]);
