function js4 = Knee_Sw_Jacobian_func(in1,in2)
%KNEE_SW_JACOBIAN_FUNC
%    JS4 = KNEE_SW_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Sep-2020 21:44:07

la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = x3+x4;
t8 = x6./2.0;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+x5;
t9 = sin(t8);
t6 = cos(t5);
t7 = t5+x6;
t10 = ls.*t3;
t11 = ls.*t4;
t16 = t5+t8;
t12 = cos(t7);
t13 = -t10;
t14 = -t11;
t17 = cos(t16);
t15 = -t12;
t20 = lt.*t9.*t17.*2.0;
t18 = t6+t15;
t19 = lt.*t18;
t21 = -t19;
js4 = reshape([1.0,0.0,t20,0.0,0.0,0.0,0.0,0.0,lt.*sin(t7),0.0,0.0,0.0,t13+t21-la.*cos(x3),0.0,0.0,0.0,0.0,0.0,t13+t21,1.0,0.0,0.0,0.0,0.0,t21,t14+t20-la.*sin(x3),0.0,0.0,0.0,0.0,lt.*t12,t14+t20,0.0,0.0,0.0,0.0],[6,6]);
