function velKsw = Knee_Sw_vel_func(in1,in2)
%KNEE_SW_VEL_FUNC
%    VELKSW = KNEE_SW_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Sep-2020 09:35:36

la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
x13 = in1(13,:);
x14 = in1(14,:);
t2 = x3+x4;
t3 = x11+x12;
t4 = t2+x5;
t5 = t3+x13;
t6 = t4+x6;
t7 = t5+x14;
t8 = cos(t6);
t9 = sin(t6);
t10 = t7.*t8;
t11 = t7.*t9;
t12 = -t11;
velKsw = reshape([t12,t10,0.0,0.0,-t10,t12,0.0,0.0,0.0,0.0,0.0,0.0,x9+lt.*t10-ls.*t3.*cos(t2)-lt.*t5.*cos(t4)-la.*x11.*cos(x3),x10+lt.*t11-ls.*t3.*sin(t2)-lt.*t5.*sin(t4)-la.*x11.*sin(x3),0.0,0.0],[4,4]);
