function velToest = Toe_St_vel_func(in1,in2)
%TOE_ST_VEL_FUNC
%    VELTOEST = TOE_ST_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Sep-2020 09:35:35

lf = in2(:,7);
x3 = in1(3,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
t2 = cos(x3);
t3 = sin(x3);
t4 = t2.*x11;
t5 = t3.*x11;
t6 = -t5;
velToest = reshape([t6,t4,0.0,0.0,-t4,t6,0.0,0.0,0.0,0.0,0.0,0.0,x9+lf.*t6,x10+lf.*t4,0.0,0.0],[4,4]);
