function js0 = Toe_St_Jacobian_func(in1,in2)
%TOE_ST_JACOBIAN_FUNC
%    JS0 = TOE_ST_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-Sep-2020 21:44:06

lf = in2(:,7);
x3 = in1(3,:);
js0 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-lf.*sin(x3),0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,lf.*cos(x3),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
