function js5 = Toe_Sw_Jacobian_func(in1,in2)
%TOE_SW_JACOBIAN_FUNC
%    JS5 = TOE_SW_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Sep-2020 09:35:39

la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+x5;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+x6;
t9 = ls.*t3;
t10 = ls.*t4;
t11 = cos(t8);
t12 = sin(t8);
t13 = t8+x7;
t14 = lt.*t7;
t17 = lt.*t6;
t20 = -t9;
t21 = -t10;
t15 = cos(t13);
t16 = sin(t13);
t18 = lt.*t11;
t19 = lt.*t12;
t22 = -t14;
t25 = -t17;
t23 = ls.*t15;
t24 = ls.*t16;
js5 = reshape([1.0,t23,t19+t22+t24,0.0,0.0,0.0,0.0,0.0,t19+t24,0.0,0.0,0.0,t18+t20+t23+t25-la.*cos(x3),0.0,t24,0.0,0.0,0.0,t18+t20+t23+t25,1.0,0.0,0.0,0.0,0.0,t18+t23+t25,t19+t21+t22+t24-la.*sin(x3),0.0,0.0,0.0,0.0,t18+t23,t19+t21+t22+t24,0.0,0.0,0.0,0.0],[6,6]);
