function js5 = Toe_Sw_Jacobian_func(in1)
%TOE_SW_JACOBIAN_FUNC
%    JS5 = TOE_SW_JACOBIAN_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Sep-2019 18:19:31

%7 Link Flat Foot with Double Support file. Only needs state as inputs, parameters are already substituted in
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+x5;
t6 = cos(t5);
t7 = sin(t5);
t8 = t5+x6;
t14 = t3.*(1.07e+2./2.5e+2);
t15 = t4.*(1.07e+2./2.5e+2);
t9 = cos(t8);
t10 = sin(t8);
t11 = t8+x7;
t16 = -t14;
t17 = -t15;
t18 = t6.*(1.07e+2./2.5e+2);
t19 = t7.*(1.07e+2./2.5e+2);
t12 = cos(t11);
t13 = sin(t11);
t20 = t9.*(1.07e+2./2.5e+2);
t21 = t10.*(1.07e+2./2.5e+2);
t22 = -t18;
t23 = -t19;
t24 = t12.*(1.07e+2./2.5e+2);
t25 = t13.*(1.07e+2./2.5e+2);
js5 = reshape([1.0,t24,t21+t23+t25,0.0,0.0,0.0,0.0,0.0,t21+t25,0.0,0.0,0.0,t16+t20+t22+t24-cos(x3).*(7.0./1.0e+2),0.0,t25,0.0,0.0,0.0,t16+t20+t22+t24,1.0,0.0,0.0,0.0,0.0,t20+t22+t24,t17+t21+t23+t25-sin(x3).*(7.0./1.0e+2),0.0,0.0,0.0,0.0,t20+t24,t17+t21+t23+t25,0.0,0.0,0.0,0.0],[6,6]);
