function posToesw = Toe_Sw_pos_func(in1,in2)
%TOE_SW_POS_FUNC
%    POSTOESW = TOE_SW_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Sep-2020 09:35:32

la = in2(:,8);
lf = in2(:,7);
ls = in2(:,6);
lt = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = x3+x4;
t3 = t2+x5;
t4 = t3+x6;
t5 = t4+x7;
t6 = t5+x8;
t7 = cos(t6);
t8 = sin(t6);
posToesw = reshape([t7,t8,0.0,0.0,-t8,t7,0.0,0.0,0.0,0.0,1.0,0.0,x1+la.*t8+lf.*t7-ls.*sin(t2)+ls.*sin(t5)-lt.*sin(t3)+lt.*sin(t4)-la.*sin(x3),x2-la.*t7+lf.*t8+ls.*cos(t2)-ls.*cos(t5)+lt.*cos(t3)-lt.*cos(t4)+la.*cos(x3),0.0,1.0],[4,4]);
