function height = swingToeClearance(q,qdot)
%SWINGTOECLEARANCE Summary of this function goes here
%   Detailed explanation goes here
global flowdata   
    la = flowdata.Parameters.Biped.la;
    lf = flowdata.Parameters.Biped.lf;
    l1 = flowdata.Parameters.Biped.ls;
    l2 = flowdata.Parameters.Biped.lt;
    slope = flowdata.Parameters.Environment.slope;
    x=[q;qdot];
    
    height=la.*cos(x(3))+l1.*cos(x(3)+x(4))+l2.*cos(x(3)+x(4)+x(5))+( ...
    -1).*l2.*cos(x(3)+x(4)+x(5)+x(6))+(-1).*l1.*cos(x(3)+x(4)+x( ...
    5)+x(6)+x(7))+(-1).*la.*cos(x(3)+x(4)+x(5)+x(6)+x(7)+x(8))+( ...
    -1).*lf.*sin(x(3)+x(4)+x(5)+x(6)+x(7)+x(8))+tan(slope).*( ...
    lf.*cos(x(3)+x(4)+x(5)+x(6)+x(7)+x(8))+la.*sin(x(3))+l1.* ...
    sin(x(3)+x(4))+l2.*sin(x(3)+x(4)+x(5))+(-1).*l2.*sin(x(3)+x( ...
    4)+x(5)+x(6))+(-1).*l1.*sin(x(3)+x(4)+x(5)+x(6)+x(7))+(-1).* ...
    la.*sin(x(3)+x(4)+x(5)+x(6)+x(7)+x(8))+(-1).*x(1))+x(2);
end

