function Pe = PE_func(in1)
%PE_FUNC
%    PE = PE_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Sep-2019 18:19:25

%7 Link Flat Foot with Double Support file. Only needs state as inputs, parameters are already substituted in
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = x3+x4;
t3 = t2+x5;
t4 = t3+x6;
t5 = t4+x7;
Pe = x2.*5.959575e+2-cos(t5+x8).*3.4335e-1+cos(t2).*2.4236250498e+2+cos(t3).*2.1400042158e+2-cos(t4).*4.106938842e+1-cos(t5).*1.270730502e+1+cos(x3).*4.1373675e+1;
