function Pe = PE_func(in1,in2)
%PE_FUNC
%    PE = PE_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Sep-2020 09:35:30

Mf = in2(:,4);
Mh = in2(:,3);
Ms = in2(:,2);
Mt = in2(:,1);
la = in2(:,8);
ls = in2(:,6);
lt = in2(:,5);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = Mh.*2.0;
t3 = Ms.*4.0;
t4 = Mt.*4.0;
t5 = x3+x4+x5;
t6 = cos(t5);
t7 = t5+x6;
t8 = cos(t7);
t9 = t7+x7;
t10 = cos(t9);
Pe = x2.*(Mf.*4.0+t2+t3+t4).*(9.81e+2./2.0e+2)+la.*cos(x3).*(Mf.*3.0+t2+t3+t4).*(9.81e+2./2.0e+2)+ls.*cos(x3+x4).*(Mf.*2.0+Ms.*3.0+t2+t4).*(9.81e+2./2.0e+2)-Mf.*ls.*t10.*(9.81e+2./1.0e+2)+Mf.*lt.*t6.*(9.81e+2./1.0e+2)-Mf.*lt.*t8.*(9.81e+2./1.0e+2)+Mh.*lt.*t6.*(9.81e+2./1.0e+2)-Ms.*ls.*t10.*(9.81e+2./2.0e+2)+Ms.*lt.*t6.*(9.81e+2./1.0e+2)-Ms.*lt.*t8.*(9.81e+2./1.0e+2)+Mt.*lt.*t6.*1.4715e+1-Mt.*lt.*t8.*(9.81e+2./2.0e+2)-Mf.*la.*cos(t9+x8).*(9.81e+2./2.0e+2);
