function velFst = Foot_St_vel_func(in1,in2)
%FOOT_ST_VEL_FUNC
%    VELFST = FOOT_ST_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-May-2020 10:16:55

x5 = in1(5,:);
x6 = in1(6,:);
velFst = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,x5,x6,0.0,0.0],[4,4]);
