function posH = Hip_pos_func(in1,in2)
%HIP_POS_FUNC
%    POSH = HIP_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-May-2020 10:16:54

a = in2(:,4);
b = in2(:,5);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = a+b;
t3 = x3+x4;
t4 = cos(t3);
t5 = sin(t3);
posH = reshape([t4,t5,0.0,0.0,-t5,t4,0.0,0.0,0.0,0.0,1.0,0.0,x1-t2.*sin(x3),x2+t2.*cos(x3),0.0,1.0],[4,4]);
