function velH = Hip_vel_func(in1,in2)
%HIP_VEL_FUNC
%    VELH = HIP_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-May-2020 10:16:55

a = in2(:,4);
b = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = a+b;
t3 = x3+x4;
t4 = x7+x8;
t5 = cos(t3);
t6 = sin(t3);
t7 = t4.*t5;
t8 = t4.*t6;
t9 = -t8;
velH = reshape([t9,t7,0.0,0.0,-t7,t9,0.0,0.0,0.0,0.0,0.0,0.0,x5-t2.*x7.*cos(x3),x6-t2.*x7.*sin(x3),0.0,0.0],[4,4]);
