function velAst = Ankle_St_vel_func(in1)
%ANKLE_ST_VEL_FUNC
%    VELAST = ANKLE_ST_VEL_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Sep-2019 18:19:28

%7 Link Flat Foot with Double Support file. Only needs state as inputs, parameters are already substituted in
x3 = in1(3,:);
x4 = in1(4,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = x3+x4;
t3 = x11+x12;
t4 = cos(t2);
t5 = sin(t2);
t6 = t3.*t4;
t7 = t3.*t5;
t8 = -t7;
velAst = reshape([t8,t6,0.0,0.0,-t6,t8,0.0,0.0,0.0,0.0,0.0,0.0,x9-x11.*cos(x3).*(7.0./1.0e+2),x10-x11.*sin(x3).*(7.0./1.0e+2),0.0,0.0],[4,4]);
