function posAst = Ankle_St_pos_func(in1)
%ANKLE_ST_POS_FUNC
%    POSAST = ANKLE_ST_POS_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Sep-2019 18:19:26

%7 Link Flat Foot with Double Support file. Only needs state as inputs, parameters are already substituted in
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
posAst = reshape([t3,t4,0.0,0.0,-t4,t3,0.0,0.0,0.0,0.0,1.0,0.0,x1-sin(x3).*(7.0./1.0e+2),x2+cos(x3).*(7.0./1.0e+2),0.0,1.0],[4,4]);
