function js3 = Hip_Jacobian_func(in1)
%HIP_JACOBIAN_FUNC
%    JS3 = HIP_JACOBIAN_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Sep-2019 18:19:31

%7 Link Flat Foot with Double Support file. Only needs state as inputs, parameters are already substituted in
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+x5;
t6 = cos(t5);
t7 = sin(t5);
t8 = t3.*(1.07e+2./2.5e+2);
t9 = t4.*(1.07e+2./2.5e+2);
t10 = -t8;
t11 = -t9;
t12 = t6.*(1.07e+2./2.5e+2);
t13 = t7.*(1.07e+2./2.5e+2);
t14 = -t12;
t15 = -t13;
js3 = reshape([1.0,0.0,t15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t10+t14-cos(x3).*(7.0./1.0e+2),0.0,0.0,0.0,0.0,0.0,t10+t14,1.0,0.0,0.0,0.0,0.0,t14,t11+t15-sin(x3).*(7.0./1.0e+2),0.0,0.0,0.0,0.0,0.0,t11+t15,0.0,0.0,0.0,0.0],[6,6]);
