function posKsw = Knee_Sw_pos_func(in1)
%KNEE_SW_POS_FUNC
%    POSKSW = KNEE_SW_POS_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Sep-2019 18:19:26

%7 Link Flat Foot with Double Support file. Only needs state as inputs, parameters are already substituted in
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = x3+x4;
t3 = t2+x5;
t4 = t3+x6;
t5 = cos(t4);
t6 = sin(t4);
posKsw = reshape([t5,t6,0.0,0.0,-t6,t5,0.0,0.0,0.0,0.0,1.0,0.0,t6.*(1.07e+2./2.5e+2)+x1-sin(t2).*(1.07e+2./2.5e+2)-sin(t3).*(1.07e+2./2.5e+2)-sin(x3).*(7.0./1.0e+2),t5.*(-1.07e+2./2.5e+2)+x2+cos(t2).*(1.07e+2./2.5e+2)+cos(t3).*(1.07e+2./2.5e+2)+cos(x3).*(7.0./1.0e+2),0.0,1.0],[4,4]);
