function js4 = Knee_Sw_Jacobian_func(in1)
%KNEE_SW_JACOBIAN_FUNC
%    JS4 = KNEE_SW_JACOBIAN_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Sep-2019 18:19:31

%7 Link Flat Foot with Double Support file. Only needs state as inputs, parameters are already substituted in
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = x3+x4;
t8 = x6./2.0;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+x5;
t9 = sin(t8);
t6 = cos(t5);
t7 = t5+x6;
t11 = t5+t8;
t13 = t3.*(1.07e+2./2.5e+2);
t14 = t4.*(1.07e+2./2.5e+2);
t10 = cos(t7);
t12 = cos(t11);
t15 = -t13;
t16 = -t14;
t17 = t6.*(1.07e+2./2.5e+2);
t18 = t10.*(1.07e+2./2.5e+2);
t19 = -t17;
t20 = t9.*t12.*(1.07e+2./1.25e+2);
js4 = reshape([1.0,0.0,t20,0.0,0.0,0.0,0.0,0.0,sin(t7).*(1.07e+2./2.5e+2),0.0,0.0,0.0,t15+t18+t19-cos(x3).*(7.0./1.0e+2),0.0,0.0,0.0,0.0,0.0,t15+t18+t19,1.0,0.0,0.0,0.0,0.0,t18+t19,t16+t20-sin(x3).*(7.0./1.0e+2),0.0,0.0,0.0,0.0,t18,t16+t20,0.0,0.0,0.0,0.0],[6,6]);
