function velKsw = Knee_Sw_vel_func(in1)
%KNEE_SW_VEL_FUNC
%    VELKSW = KNEE_SW_VEL_FUNC(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    23-Sep-2019 18:19:29

%7 Link Flat Foot with Double Support file. Only needs state as inputs, parameters are already substituted in
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
x13 = in1(13,:);
x14 = in1(14,:);
t2 = x3+x4;
t3 = x11+x12;
t4 = t2+x5;
t5 = t3+x13;
t6 = t4+x6;
t7 = t5+x14;
t8 = cos(t6);
t9 = sin(t6);
t10 = t7.*t8;
t11 = t7.*t9;
t12 = -t11;
velKsw = reshape([t12,t10,0.0,0.0,-t10,t12,0.0,0.0,0.0,0.0,0.0,0.0,t10.*(1.07e+2./2.5e+2)+x9-t3.*cos(t2).*(1.07e+2./2.5e+2)-t5.*cos(t4).*(1.07e+2./2.5e+2)-x11.*cos(x3).*(7.0./1.0e+2),t11.*(1.07e+2./2.5e+2)+x10-t3.*sin(t2).*(1.07e+2./2.5e+2)-t5.*sin(t4).*(1.07e+2./2.5e+2)-x11.*sin(x3).*(7.0./1.0e+2),0.0,0.0],[4,4]);
