function out1 = A_KLockSw_func(in1,in2)
%A_KLOCKSW_FUNC
%    OUT1 = A_KLOCKSW_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:09

%
out1 = [0.0,0.0,0.0,0.0,0.0,1.0];
