function out1 = A_VHC_func(in1,in2)
%A_VHC_FUNC
%    OUT1 = A_VHC_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:09

%
ls = in2(:,7);
lt = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = x3+x4;
t3 = sin(t2);
t4 = t2+x5;
t5 = sin(t4);
t6 = t4+x6;
t7 = sin(t6);
t9 = t3+t5;
t8 = ls.*t7;
t10 = lt.*t9;
out1 = [0.0,0.0,t10+ls.*(t7+sin(x3)),t8+t10,t8+lt.*t5,t8];
