function out1 = Adot_VHC_func(in1,in2)
%ADOT_VHC_FUNC
%    OUT1 = ADOT_VHC_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:10

%
ls = in2(:,7);
lt = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = x3+x4;
t3 = x9+x10;
t4 = cos(t2);
t5 = t2+x5;
t6 = t3+x11;
t7 = cos(t5);
t8 = t5+x6;
t9 = t6+x12;
t11 = t3.*t4;
t10 = cos(t8);
t12 = t6.*t7;
t13 = ls.*t9.*t10;
t14 = t11+t12;
t15 = lt.*t14;
out1 = [0.0,0.0,t15+ls.*(t9.*t10+x9.*cos(x3)),t13+t15,t13+lt.*t12,t13];
