function Adotswap = Adot_Swap_func(in1,in2)
%ADOT_SWAP_FUNC
%    ADOTSWAP = ADOT_SWAP_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:09

%
ls = in2(:,7);
lt = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = x3+x4;
t3 = x9+x10;
t4 = cos(t2);
t5 = sin(t2);
t6 = t2+x5;
t7 = t3+x11;
t8 = cos(t6);
t9 = sin(t6);
t10 = t6+x6;
t11 = t7+x12;
t14 = lt.*t3.*t4;
t15 = lt.*t3.*t5;
t12 = cos(t10);
t13 = sin(t10);
t16 = lt.*t7.*t8;
t17 = lt.*t7.*t9;
t18 = -t14;
t19 = ls.*t11.*t12;
t20 = ls.*t11.*t13;
t21 = -t17;
t22 = -t20;
Adotswap = reshape([0.0,0.0,0.0,0.0,t15+t21+t22+ls.*x9.*sin(x3),t16+t18+t19-ls.*x9.*cos(x3),t15+t21+t22,t16+t18+t19,t21+t22,t16+t19,t22,t19],[2,6]);
