function out1 = Adot_KLockSt_func(in1,in2)
%ADOT_KLOCKST_FUNC
%    OUT1 = ADOT_KLOCKST_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:10

%
out1 = [0.0,0.0,0.0,0.0,0.0,0.0];
