function out1 = C_func(in1,in2)
%C_FUNC
%    OUT1 = C_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Jun-2020 13:17:48

out1 = reshape([0.0,0.0,0.0,0.0],[2,2]);
