function M = M_func(in1,in2)
%M_FUNC
%    M = M_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Jun-2020 13:17:48

m = in2(:,2);
M = reshape([m,0.0,0.0,m],[2,2]);
