function l = Spring_Length_func(in1,in2)
%SPRING_LENGTH_FUNC
%    L = SPRING_LENGTH_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Jun-2020 13:17:49

x1 = in1(1,:);
x2 = in1(2,:);
xf = in2(1,:);
yf = in2(2,:);
l = sqrt((x1-xf).^2+(x2-yf).^2);
