function ldot = Spring_Velocity_func(in1,in2)
%SPRING_VELOCITY_FUNC
%    LDOT = SPRING_VELOCITY_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Jun-2020 13:17:49

x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
xf = in2(1,:);
yf = in2(2,:);
t2 = -xf;
t3 = -yf;
t4 = t2+x1;
t5 = t3+x2;
ldot = 1.0./sqrt(t4.^2+t5.^2).*(t4.*x3+t5.*x4);
