function posCoM = COM_pos_func(in1,in2)
%COM_POS_FUNC
%    POSCOM = COM_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:17

%
Mh = in2(:,3);
Ms = in2(:,4);
Mt = in2(:,5);
ls = in2(:,7);
lt = in2(:,8);
rs = in2(:,9);
rt = in2(:,10);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = Ms.*rs;
t3 = Mt.*rt;
t4 = x3+x4;
t5 = Ms.*2.0;
t6 = Mt.*2.0;
t7 = Ms+Mt;
t10 = -rs;
t8 = Mh+t7;
t9 = t4+x5;
t12 = lt.*t7;
t14 = ls+t10;
t15 = Mh+Ms+t6;
t17 = Mh+t5+t6;
t11 = t9+x6;
t13 = lt.*t8;
t16 = -t12;
t18 = ls.*t15;
t21 = 1.0./t17;
t19 = t3+t13;
t20 = t3+t16;
t22 = t2+t18;
posCoM = [-t21.*(-t17.*x1+t19.*sin(t4)+t20.*sin(t9)+t22.*sin(x3)-Ms.*t14.*sin(t11)),t21.*(t17.*x2+t19.*cos(t4)+t20.*cos(t9)+t22.*cos(x3)-Ms.*t14.*cos(t11)),0.0];
