function velFsw = Foot_Sw_vel_func(in1,in2)
%FOOT_SW_VEL_FUNC
%    VELFSW = FOOT_SW_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:18

%
ls = in2(:,7);
lt = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
x12 = in1(12,:);
t2 = x3+x4;
t3 = x9+x10;
t4 = t2+x5;
t5 = t3+x11;
t6 = t4+x6;
t7 = t5+x12;
t8 = cos(t6);
t9 = sin(t6);
t10 = t7.*t8;
t11 = t7.*t9;
t12 = -t11;
velFsw = reshape([t12,t10,0.0,0.0,-t10,t12,0.0,0.0,0.0,0.0,0.0,0.0,x7+ls.*t10-lt.*t3.*cos(t2)+lt.*t5.*cos(t4)-ls.*x9.*cos(x3),x8+ls.*t11-lt.*t3.*sin(t2)+lt.*t5.*sin(t4)-ls.*x9.*sin(x3),0.0,0.0],[4,4]);
