function velFst = Foot_St_vel_func(in1,in2)
%FOOT_ST_VEL_FUNC
%    VELFST = FOOT_ST_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:17

%
x7 = in1(7,:);
x8 = in1(8,:);
velFst = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,x7,x8,0.0,0.0],[4,4]);
