function velH = Hip_vel_func(in1,in2)
%HIP_VEL_FUNC
%    VELH = HIP_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:18

%
ls = in2(:,7);
lt = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
t2 = x3+x4;
t3 = x9+x10;
t4 = cos(t2);
t5 = sin(t2);
t6 = t3.*t4;
t7 = t3.*t5;
t8 = -t7;
velH = reshape([t8,t6,0.0,0.0,-t6,t8,0.0,0.0,0.0,0.0,0.0,0.0,x7-lt.*t6-ls.*x9.*cos(x3),x8+lt.*t8-ls.*x9.*sin(x3),0.0,0.0],[4,4]);
