function out1 = Knee_Sw_Jacobian_func(in1,in2)
%KNEE_SW_JACOBIAN_FUNC
%    OUT1 = KNEE_SW_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:19

%
ls = in2(:,7);
lt = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = x3+x4;
t3 = cos(t2);
t4 = sin(t2);
t5 = t2+x5;
t6 = cos(t5);
t7 = sin(t5);
t8 = -t3;
t9 = -t4;
t10 = t6+t8;
t11 = t7+t9;
t12 = -lt.*(t3-t6);
t13 = -lt.*(t4-t7);
out1 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,t12-ls.*cos(x3),t13-ls.*sin(x3),0.0,0.0,0.0,t6,t12,t13,0.0,0.0,0.0,t6,lt.*t6,lt.*t7,0.0,0.0,0.0,t6,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
