function posKsw = Knee_Sw_pos_func(in1,in2)
%KNEE_SW_POS_FUNC
%    POSKSW = KNEE_SW_POS_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:16

%
ls = in2(:,7);
lt = in2(:,8);
x1 = in1(1,:);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
t2 = x3+x4;
t3 = t2+x5;
t4 = cos(t3);
t5 = sin(t3);
posKsw = reshape([t4,t5,0.0,0.0,-t5,t4,0.0,0.0,0.0,0.0,1.0,0.0,x1-ls.*sin(x3)+lt.*(t5-sin(t2)),x2+ls.*cos(x3)-lt.*(t4-cos(t2)),0.0,1.0],[4,4]);
