function out1 = Knee_St_Jacobian_func(in1,in2)
%KNEE_ST_JACOBIAN_FUNC
%    OUT1 = KNEE_ST_JACOBIAN_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:19

%
ls = in2(:,7);
x3 = in1(3,:);
t2 = cos(x3);
out1 = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,-ls.*t2,-ls.*sin(x3),0.0,0.0,0.0,t2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
