function velKsw = Knee_Sw_vel_func(in1,in2)
%KNEE_SW_VEL_FUNC
%    VELKSW = KNEE_SW_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:18

%
ls = in2(:,7);
lt = in2(:,8);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
x10 = in1(10,:);
x11 = in1(11,:);
t2 = x3+x4;
t3 = x9+x10;
t4 = t2+x5;
t5 = t3+x11;
t6 = cos(t4);
t7 = sin(t4);
t8 = t5.*t6;
t9 = t5.*t7;
t10 = -t9;
velKsw = reshape([t10,t8,0.0,0.0,-t8,t10,0.0,0.0,0.0,0.0,0.0,0.0,x7+lt.*(t8-t3.*cos(t2))-ls.*x9.*cos(x3),x8+lt.*(t9-t3.*sin(t2))-ls.*x9.*sin(x3),0.0,0.0],[4,4]);
