function velKst = Knee_St_vel_func(in1,in2)
%KNEE_ST_VEL_FUNC
%    VELKST = KNEE_ST_VEL_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:17

%
ls = in2(:,7);
x3 = in1(3,:);
x7 = in1(7,:);
x8 = in1(8,:);
x9 = in1(9,:);
t2 = cos(x3);
t3 = sin(x3);
t4 = t2.*x9;
t5 = t3.*x9;
t6 = -t5;
velKst = reshape([t6,t4,0.0,0.0,-t4,t6,0.0,0.0,0.0,0.0,0.0,0.0,x7-ls.*t4,x8+ls.*t6,0.0,0.0],[4,4]);
