function ljacob2 = Spring_Jacobian_2_func(in1,in2)
%SPRING_JACOBIAN_2_FUNC
%    LJACOB2 = SPRING_JACOBIAN_2_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:20

%
ls = in2(:,3);
lt = in2(:,4);
x6 = in1(6,:);
ljacob2 = [0.0;0.0;0.0;0.0;0.0;-ls.*lt.*sin(x6).*1.0./sqrt(ls.^2+lt.^2+ls.*lt.*cos(x6).*2.0)];
