function l1dot = Spring_Velocity_1_func(in1,in2)
%SPRING_VELOCITY_1_FUNC
%    L1DOT = SPRING_VELOCITY_1_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:20

%
ls = in2(:,3);
lt = in2(:,4);
x4 = in1(4,:);
x10 = in1(10,:);
l1dot = -ls.*lt.*x10.*sin(x4).*1.0./sqrt(ls.^2+lt.^2+ls.*lt.*cos(x4).*2.0);
