function l1 = Spring_Length_1_func(in1,in2)
%SPRING_LENGTH_1_FUNC
%    L1 = SPRING_LENGTH_1_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:19

%
ls = in2(:,3);
lt = in2(:,4);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x3+x4;
l1 = sqrt((lt.*cos(t2)+ls.*cos(x3)).^2+(lt.*sin(t2)+ls.*sin(x3)).^2);
