function ljacob1 = Spring_Jacobian_1_func(in1,in2)
%SPRING_JACOBIAN_1_FUNC
%    LJACOB1 = SPRING_JACOBIAN_1_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:20

%
ls = in2(:,3);
lt = in2(:,4);
x4 = in1(4,:);
ljacob1 = [0.0;0.0;0.0;-ls.*lt.*sin(x4).*1.0./sqrt(ls.^2+lt.^2+ls.*lt.*cos(x4).*2.0);0.0;0.0];
