function l2dot = Spring_Velocity_2_func(in1,in2)
%SPRING_VELOCITY_2_FUNC
%    L2DOT = SPRING_VELOCITY_2_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:20

%
ls = in2(:,3);
lt = in2(:,4);
x6 = in1(6,:);
x12 = in1(12,:);
l2dot = -ls.*lt.*x12.*sin(x6).*1.0./sqrt(ls.^2+lt.^2+ls.*lt.*cos(x6).*2.0);
