function ke = KE_func(in1,in2)
%KE_FUNC
%    KE = KE_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Jun-2020 13:17:49

m = in2(:,2);
x3 = in1(3,:);
x4 = in1(4,:);
ke = (m.*(x3.^2+x4.^2))./2.0;
