function Pe = PE_func(in1,in2)
%PE_FUNC
%    PE = PE_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Jun-2020 13:17:49

g = in2(:,1);
m = in2(:,2);
x2 = in1(2,:);
Pe = g.*m.*x2;
