function Cmat = C_func(in1,in2)
%C_FUNC
%    CMAT = C_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-May-2020 10:16:52

Mh = in2(:,2);
Ms = in2(:,3);
a = in2(:,4);
b = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = sin(x4);
t3 = a+b;
t4 = x3+x4;
t5 = x7+x8;
t6 = Ms.*2.0;
t7 = Mh+Ms;
t8 = cos(t4);
t9 = sin(t4);
t10 = Mh+t6;
t11 = a.*t7;
t12 = b.*t10;
t13 = t11+t12;
Cmat = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,x7.*(t13.*sin(x3)-Ms.*a.*t9)-Ms.*a.*t9.*x8,-x7.*(t13.*cos(x3)-Ms.*a.*t8)+Ms.*a.*t8.*x8,Ms.*a.*t2.*t3.*x8,-Ms.*a.*t2.*t3.*x7,-Ms.*a.*t5.*t9,Ms.*a.*t5.*t8,Ms.*a.*t2.*t3.*t5,0.0],[4,4]);
