function ddCoM = COM_accel_func(in1,in2,in3)
%COM_ACCEL_FUNC
%    DDCOM = COM_ACCEL_FUNC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-May-2020 10:16:52

Mh = in3(:,2);
Ms = in3(:,3);
a = in3(:,4);
ac1 = in2(1,:);
ac2 = in2(2,:);
ac3 = in2(3,:);
ac4 = in2(4,:);
b = in3(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = cos(x3);
t3 = sin(x3);
t4 = ac3+ac4;
t5 = a+b;
t6 = x3+x4;
t7 = x7+x8;
t8 = Ms.*2.0;
t9 = b.*2.0;
t10 = x7.^2;
t11 = cos(t6);
t12 = sin(t6);
t13 = Mh+t8;
t14 = b+t5;
t15 = t7.^2;
t16 = Mh.*t5;
t17 = Ms.*t14;
t18 = 1.0./t13;
t19 = t16+t17;
ddCoM = [t18.*(ac1.*t13-ac3.*t2.*t19+t3.*t10.*t19+Ms.*a.*t4.*t11-Ms.*a.*t12.*t15),t18.*(ac2.*t13-ac3.*t3.*t19-t2.*t10.*t19+Ms.*a.*t4.*t12+Ms.*a.*t11.*t15),0.0];
