function G = G_func(in1,in2)
%G_FUNC
%    G = G_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-May-2020 10:16:52

Mh = in2(:,2);
Ms = in2(:,3);
a = in2(:,4);
b = in2(:,5);
g = in2(:,6);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x3+x4;
t3 = sin(t2);
G = [0.0;g.*(Mh+Ms.*2.0);-g.*(sin(x3).*(Ms.*(a+b.*2.0)+Mh.*(a+b))-Ms.*a.*t3);Ms.*a.*g.*t3];
