function M = M_func(in1,in2)
%M_FUNC
%    M = M_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    29-May-2020 10:16:51

Isz = in2(:,1);
Mh = in2(:,2);
Ms = in2(:,3);
a = in2(:,4);
b = in2(:,5);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x3);
t3 = cos(x4);
t4 = sin(x3);
t5 = sin(x4);
t6 = a+b;
t7 = x3+x4;
t8 = t2.^2;
t9 = t4.^2;
t10 = cos(t7);
t11 = sin(t7);
t12 = t6.^2;
t13 = Ms.*b.*t2;
t14 = Ms.*b.*t4;
t17 = t3.*t6;
t22 = Mh.*t2.*t6;
t23 = Mh.*t4.*t6;
t15 = t10.^2;
t16 = t11.^2;
t18 = Mh.*t8;
t19 = Ms.*t8;
t20 = Mh.*t9;
t21 = Ms.*t9;
t24 = Ms.*a.*t10;
t25 = Ms.*a.*t11;
t26 = -t13;
t27 = -t14;
t28 = -t17;
t31 = -t22;
t32 = -t23;
t34 = Ms.*t5.*t6.*t10;
t35 = Ms.*t5.*t6.*t11;
t29 = Ms.*t15;
t30 = Ms.*t16;
t33 = a+t28;
t37 = -t35;
t36 = Ms.*a.*t33;
t39 = Ms.*t10.*t33;
t40 = Ms.*t11.*t33;
t41 = t18+t19+t20+t21+t29+t30;
t38 = Isz+t36;
t42 = t27+t32+t34+t40;
t43 = t26+t31+t37+t39;
M = reshape([t41,0.0,t43,t24,0.0,t41,t42,t25,t43,t42,Isz.*2.0+Mh.*t12+Ms.*b.^2+Ms.*t33.^2+Ms.*t5.^2.*t12,t38,t24,t25,t38,Isz+Ms.*a.^2],[4,4]);
