function Pe = PE_func(in1,in2)
%PE_FUNC
%    PE = PE_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    18-Apr-2020 15:46:15

%
Mh = in2(:,3);
Ms = in2(:,4);
Mt = in2(:,5);
g = in2(:,6);
ls = in2(:,7);
lt = in2(:,8);
rs = in2(:,9);
rt = in2(:,10);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
t2 = cos(x3);
t3 = cos(x4);
t4 = cos(x5);
t5 = cos(x6);
t6 = sin(x3);
t7 = sin(x4);
t8 = sin(x5);
t9 = sin(x6);
t10 = ls+lt;
t11 = ls+rt;
t12 = t2.*t3;
t13 = t2.*t7;
t14 = t3.*t6;
t15 = t6.*t7;
t16 = t3-1.0;
t17 = t4-1.0;
t18 = ls.*t15;
t19 = -t15;
t20 = ls.*t2.*t16;
t21 = t13+t14;
t22 = -t20;
t23 = t12+t19;
t24 = t4.*t21;
t25 = t8.*t21;
t26 = t4.*t23;
t27 = t8.*t23;
t28 = -t25;
t29 = t10.*t25;
t30 = t10.*t17.*t23;
t31 = -t30;
t32 = t24+t27;
t33 = t26+t28;
Pe = Mh.*g.*(t18+t22+x2+t10.*t23)+Mt.*g.*(t18+t22+x2+t11.*t23)+Ms.*g.*(x2+rs.*t2)+Mt.*g.*(t18+t22+t29+t31+x2-t11.*(t25-t26))+Ms.*g.*(t18+t22+t29+t31+x2-rs.*(t9.*t32+t5.*(t25-t26))+ls.*(t25-t26).*(t5-1.0)+ls.*t9.*t32);
