function Ke = KE_func(in1,in2)
%KE_FUNC
%    KE = KE_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 10:54:27

%Prosthesis file. Needs state and parameters as inputs
Mf = in2(:,2);
Ms = in2(:,1);
la = in2(:,5);
lf = in2(:,6);
ls = in2(:,4);
lt = in2(:,3);
x3 = in1(3,:);
x4 = in1(4,:);
x5 = in1(5,:);
x6 = in1(6,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = cos(x3);
t3 = cos(x4);
t4 = sin(x3);
t5 = sin(x4);
t6 = x3+x4;
t13 = -lt;
t14 = la.*(3.0./2.0);
t15 = lf./4.0;
t16 = ls./2.0;
t7 = t2.^2;
t8 = t4.^2;
t9 = ls.*t3;
t10 = cos(t6);
t11 = ls.*t5;
t12 = sin(t6);
t26 = t13+t14;
t27 = la+t13+t16;
t17 = t10.^2;
t18 = t12.^2;
t19 = Ms.*t7;
t20 = Ms.*t8;
t23 = Mf.*t10.*t15;
t24 = Mf.*t12.*t15;
t25 = t11+t15;
t28 = Mf.*lf.*t10.*(-1.0./4.0);
t29 = t9+t26;
t30 = Ms.*t2.*t27;
t31 = Ms.*t4.*t27;
t34 = Mf.*t10.*t26;
t35 = Mf.*t12.*t26;
t21 = Mf.*t17;
t22 = Mf.*t18;
t32 = Mf.*t10.*t25;
t33 = Mf.*t12.*t25;
t36 = Mf.*t15.*t25;
t38 = Mf.*t12.*t29;
t39 = Mf.*t10.*t29;
t40 = Mf.*t26.*t29;
t41 = t24+t34;
t42 = t28+t35;
t37 = -t32;
t43 = t19+t20+t21+t22;
t44 = t36+t40;
t45 = t30+t33+t39;
t46 = t31+t37+t38;
Ke = x6.*(x8.*(t35-(Mf.*lf.*t10)./4.0)-t43.*x6+t46.*x7).*(-1.0./2.0)-(x5.*(-t43.*x5+t41.*x8+t45.*x7))./2.0+(x8.*(x8.*((Mf.*lf.^2)./1.6e+1+Mf.*t26.^2)-x6.*(t35-(Mf.*lf.*t10)./4.0)-t41.*x5+t44.*x7))./2.0-(x7.*(t45.*x5-t44.*x8+t46.*x6-x7.*(Mf.*t25.^2+Mf.*t29.^2+Ms.*t27.^2)))./2.0;
