function Pe = PE_func(in1,in2)
%PE_FUNC
%    PE = PE_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 10:54:27

%Prosthesis file. Needs state and parameters as inputs
Mf = in2(:,2);
Ms = in2(:,1);
la = in2(:,5);
lf = in2(:,6);
ls = in2(:,4);
lt = in2(:,3);
x2 = in1(2,:);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x3);
t3 = x3+x4;
t4 = -lt;
Pe = Mf.*(lt+x2+ls.*t2+(lf.*sin(t3))./4.0+cos(t3).*(la.*(3.0./2.0)+t4)).*(9.81e+2./1.0e+2)+Ms.*(lt+x2+t2.*(la+ls./2.0+t4)).*(9.81e+2./1.0e+2);
