function Cmat = C_func(in1,in2)
%C_FUNC
%    CMAT = C_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 10:54:24

%Prosthesis file. Needs state and parameters as inputs
Mf = in2(:,2);
Ms = in2(:,1);
la = in2(:,5);
lf = in2(:,6);
ls = in2(:,4);
lt = in2(:,3);
x3 = in1(3,:);
x4 = in1(4,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = cos(x4);
t3 = sin(x4);
t4 = x3+x4;
t5 = x7+x8;
t6 = la.*6.0;
t7 = lt.*4.0;
t8 = lf.*t2;
t9 = cos(t4);
t10 = sin(t4);
t11 = -t7;
t12 = lf.*t9;
t13 = lf.*t10;
t14 = -t8;
t16 = t6+t11;
t15 = -t12;
t17 = t3.*t16;
t18 = t9.*t16;
t19 = t10.*t16;
t20 = t14+t17;
t21 = t13+t18;
t22 = t15+t19;
Cmat = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(x7.*(sin(x3).*(Ms.*la.*4.0+Mf.*ls.*4.0+Ms.*ls.*2.0-Ms.*lt.*4.0)+Mf.*t15+Mf.*t19))./4.0-(Mf.*x8.*(t12-t19))./4.0,x7.*(Mf.*t21+cos(x3).*(ls.*(Mf.*2.0+Ms).*2.0+Ms.*(la.*2.0-lt.*2.0).*2.0)).*(-1.0./4.0)-(Mf.*t21.*x8)./4.0,(Mf.*ls.*x8.*(t8-t17))./4.0,Mf.*ls.*x7.*(t8-t17).*(-1.0./4.0),Mf.*t5.*(t12-t19).*(-1.0./4.0),Mf.*t5.*t21.*(-1.0./4.0),(Mf.*ls.*t5.*(t8-t17))./4.0,0.0],[4,4]);
