function ddCoM = COM_accel_func(in1,in2,in3)
%COM_ACCEL_FUNC
%    DDCOM = COM_ACCEL_FUNC(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 10:54:25

Mf = in3(:,2);
Ms = in3(:,1);
a1 = in2(1,:);
a2 = in2(2,:);
a3 = in2(3,:);
a4 = in2(4,:);
la = in3(:,5);
lf = in3(:,6);
ls = in3(:,4);
lt = in3(:,3);
x3 = in1(3,:);
x4 = in1(4,:);
x7 = in1(7,:);
x8 = in1(8,:);
t2 = cos(x3);
t3 = sin(x3);
t4 = a3+a4;
t5 = x3+x4;
t6 = x7+x8;
t7 = la.*2.0;
t8 = la.*6.0;
t9 = lt.*2.0;
t10 = lt.*4.0;
t11 = x7.^2;
t12 = Mf+Ms;
t13 = Mf.*ls.*4.0;
t15 = -a2;
t17 = -lt;
t21 = la.*(3.0./2.0);
t22 = ls./2.0;
t14 = cos(t5);
t16 = sin(t5);
t18 = -t9;
t19 = -t10;
t20 = t6.^2;
t23 = 1.0./t12;
t26 = t17+t21;
t27 = la+t17+t22;
t24 = t8+t19;
t25 = ls+t7+t18;
t28 = Ms.*t25.*2.0;
t29 = t13+t28;
ddCoM = [t23.*(a1.*t12.*-4.0+a3.*t2.*t29-t3.*t11.*t29+Mf.*lf.*t4.*t16+Mf.*lf.*t14.*t20+Mf.*t4.*t14.*t24-Mf.*t16.*t20.*t24).*(-1.0./4.0),-t23.*(Mf.*(t15+a3.*ls.*t3-(lf.*t4.*t14)./4.0+(lf.*t16.*t20)./4.0+ls.*t2.*t11+t4.*t16.*t26+t14.*t20.*t26)+Ms.*(t15+a3.*t3.*t27+t2.*t11.*t27)),0.0];
