function G = G_func(in1,in2)
%G_FUNC
%    G = G_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 10:54:25

%Prosthesis file. Needs state and parameters as inputs
Mf = in2(:,2);
Ms = in2(:,1);
la = in2(:,5);
lf = in2(:,6);
ls = in2(:,4);
lt = in2(:,3);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = x3+x4;
t3 = la.*6.0;
t4 = lt.*4.0;
t5 = cos(t2);
t6 = sin(t2);
t7 = -t4;
t8 = t3+t7;
G = [0.0;Mf.*(9.81e+2./1.0e+2)+Ms.*(9.81e+2./1.0e+2);sin(x3).*(Ms.*(la.*2.0+ls-lt.*2.0).*2.0+Mf.*ls.*4.0).*(-9.81e+2./4.0e+2)+Mf.*lf.*t5.*(9.81e+2./4.0e+2)-Mf.*t6.*t8.*(9.81e+2./4.0e+2);Mf.*(lf.*t5-t6.*t8).*(9.81e+2./4.0e+2)];
