function M = M_func(in1,in2)
%M_FUNC
%    M = M_FUNC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.3.
%    27-Jan-2020 10:54:24

%Prosthesis file. Needs state and parameters as inputs
Mf = in2(:,2);
Ms = in2(:,1);
la = in2(:,5);
lf = in2(:,6);
ls = in2(:,4);
lt = in2(:,3);
x3 = in1(3,:);
x4 = in1(4,:);
t2 = cos(x3);
t3 = cos(x4);
t4 = sin(x3);
t5 = sin(x4);
t6 = x3+x4;
t13 = -lt;
t14 = la.*(3.0./2.0);
t15 = lf./4.0;
t16 = ls./2.0;
t7 = t2.^2;
t8 = t4.^2;
t9 = ls.*t3;
t10 = cos(t6);
t11 = ls.*t5;
t12 = sin(t6);
t26 = t13+t14;
t27 = la+t13+t16;
t17 = t10.^2;
t18 = t12.^2;
t19 = Ms.*t7;
t20 = Ms.*t8;
t23 = Mf.*t10.*t15;
t24 = Mf.*t12.*t15;
t25 = t11+t15;
t28 = Mf.*lf.*t12.*(-1.0./4.0);
t29 = t9+t26;
t30 = Ms.*t2.*t27;
t31 = Ms.*t4.*t27;
t34 = Mf.*t10.*t26;
t35 = Mf.*t12.*t26;
t21 = Mf.*t17;
t22 = Mf.*t18;
t32 = Mf.*t10.*t25;
t33 = Mf.*t12.*t25;
t36 = Mf.*t15.*t25;
t37 = -t30;
t38 = -t31;
t40 = -t34;
t41 = -t35;
t42 = Mf.*t12.*t29;
t43 = Mf.*t10.*t29;
t46 = Mf.*t26.*t29;
t39 = -t33;
t44 = -t42;
t45 = -t43;
t47 = t23+t41;
t48 = t19+t20+t21+t22;
t49 = t28+t40;
t50 = t36+t46;
t51 = t32+t38+t44;
t52 = t37+t39+t45;
M = reshape([t48,0.0,t52,t49,0.0,t48,t51,t47,t52,t51,Mf.*t25.^2+Mf.*t29.^2+Ms.*t27.^2,t50,t49,t47,t50,(Mf.*lf.^2)./1.6e+1+Mf.*t26.^2],[4,4]);
